PATCH http://localhost:8081/api/v1/user
Content-Type: application/json

{
  "id": "7",
  "name": "testtest"
}

###修改




POST http://localhost:8081/api/v1/user
Content-Type: application/json

{
  "id": "7",
  "name": "test"
}

###添加




GET http://localhost:8081/api/v1/user/1
Accept: application/json


###根据id查询



GET http://localhost:8081/api/v1/users
Accept: application/json


###查询所有

DELETE  http://localhost:8081/api/v1/user/7
Accept: application/json


###删除